<?php if ( ! defined( 'ABSPATH' ) ) { die; } // Cannot access pages directly.

/**
 *
 * Templates
 * @author ThemeStek
 * 
 */
class THEMESTEK_liviza_templates {
	public static function get( $n = 'x' ) {

		/* Set theme default color */
		$liviza_theme_options = get_option('liviza_theme_options');
		if ( ! empty( $liviza_theme_options['skincolor'] ) ) {
			$color = $liviza_theme_options['skincolor'];
		}else{
			$color = '#000000';
		}

		/* Set theme default Image & Video */
		$imgu = 'http://www.thememount.com/img/';
		$img = 'http://www.thememount.com/img/1000x1000.jpg';
		$vid = 'http://www.youtube.com/watch?v=AvWjf_RUy4c';


		$p = array(
				array(
					'section'	=> array('Service Box'),
					'name'		=> esc_attr('1.jpg'),
					'img'		=> '1.jpg',
					'content'	=> '[vc_row themestek_textcolor="white" themestek_bgcolor="darkgrey" full_width="stretch_row" css=".vc_custom_1579083957325{padding-bottom: 200px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-bg-pattarn-2"][vc_column zindex="1"]
					[vc_row_inner][vc_column_inner width="1/2"][themestek-heading h2="Liviza Immigration Visa<br />
					<em>Service We Provide</em>" h4="Our Service"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1576219307436{margin-top: 35px !important;}"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text][/vc_column_inner][/vc_row_inner][themestek-servicebox h2="" boxstyle="style-1" show="-1" column="four" boxview="carousel" carousel_dots="1" carousel_nav="hide"][/themestek-servicebox][/vc_column][/vc_row]',
					
				),
				array(
					'section'	=> array('Service Box'),
					'name'		=> esc_attr('2.jpg'),
					'img'		=> '2.jpg',
					'content'	=> '[vc_row themestek_bgimage_position="center_bottom" css=".vc_custom_1577957491383{padding-top: 0px !important;padding-bottom: 40px !important;background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2019/12/bg-pattarn-02.png?id=12913) !important;background-position: 0 0 !important;background-repeat: no-repeat !important;}" el_class="themestek-servicebox-style-2-space"][vc_column][themestek-servicebox h2="Immigration - Choose<em> your country!</em>" h4="Immigration" boxstyle="style-2"]With a community of over 400 million users and a majority age group being 18 to 29 wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/themestek-servicebox][/vc_column][/vc_row]',
					
				),
				array(
					'section'	=> array('About'),
					'name'		=> esc_attr('3.jpg'),
					'img'		=> '3.jpg',
					'content'	=> '[vc_row themestek_responsive_css="66659895|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2" css=".vc_custom_1576296341647{padding-bottom: 150px !important;}"][vc_single_image image="13722" img_size="470*470" el_class="ts-image-shadow-1 ts-border-radius-1"][vc_single_image image="13721" img_size="370*275" el_class="ts-promo-image-1 ts-border-radius-1"][themestek-icon type="themestek_liviza_business_icon" icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" color="white" background_style="rounded" background_color="skincolor" size="xl" el_class="ts-brand-icon"][/vc_column][vc_column width="1/2" css=".vc_custom_1576297121934{padding-top: 30px !important;}"][themestek-heading h2="Immigration Services From<br />
					<em>Experienced Lawyers.</em>" h4="About Agency"][/themestek-heading][vc_custom_heading text="Weve been counselling students for educational Opportun in Foreign countries." font_container="tag:h3|font_size:22px|text_align:left|line_height:36px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][vc_column_text]Fusce non mi at nisl laoreet pretium. Nulla ut elementum sapien, a pulvinar augue. Sed semper sed tellus in ultrices. Nam hendrerit elit vel urna fermentum congue.[/vc_column_text][themestek-list icon_type="themestek_liviza_business_icon" icon_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-check" line1="VGFsayUyMHRvJTIwb25lJTIwb2YlMjBvdXIlMjBiZXN0JTIwY29uc3VsdGFudCUyMHRvZGF5" line2="T3VyJTIwZXhwZXJ0cyUyMGFyZSUyMGFibGUlMjB0byUyMGZpbmQlMjBuZXclMjBncm93dGg=" line3="RmluZCUyMG1vcmUlMjBpbmZvcm1hdGlvbiUyMG91ciUyMHdlYnNpdGU=" el_class="themestek-list-sep"][themestek-btn title="Discover More" style="classic" css=".vc_custom_1579859167461{margin-top: 25px !important;}"][/vc_column][/vc_row]',
															
				),

				array(
					'section'	=> array('About', 'Skill'),
					'name'		=> esc_attr('4.jpg'),
					'img'		=> '4.jpg',
					'content'	=> '[vc_row themestek_responsive_css="74138818|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2"][vc_single_image image="13722" img_size="full" el_class="ts-image-shadow-1 ts-border-radius-1" css=".vc_custom_1582003077006{margin-bottom: 20px !important;}"][themestek-icon type="fontawesome" icon_fontawesome="fa fa-play" color="white" background_style="rounded" background_color="skincolor" size="xl" align="right" el_class="ts-brand-icon-1"][/vc_column][vc_column width="1/2" css=".vc_custom_1579685179319{padding-top: 30px !important;padding-left: 60px !important;}" themestek_responsive_css="52206995|colbreak_no||||||15||15|colbreak_no|||||||||colbreak_no||||||||||colbreak_no|||||||||"][themestek-heading h2="Immigration Services From<br />
<em>Experienced Lawyers</em>" h4="About Agency"][/themestek-heading][vc_custom_heading text="Weve been counselling students for educational Opportun in Foreign countries." font_container="tag:h3|font_size:22px|text_align:left|line_height:36px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][vc_column_text]Fusce non mi at nisl laoreet pretium. Nulla ut elementum sapien, a pulvinar augue. Sed semper sed tellus in ultrices. Nam hendrerit elit vel urna fermentum congue.[/vc_column_text][themestek-progress-bar values="%5B%7B%22label%22%3A%22Student%20Consultency%22%2C%22value%22%3A%2290%22%2C%22add_icon%22%3A%22true%22%2C%22i_type%22%3A%22fontawesome%22%2C%22i_icon_fontawesome%22%3A%22fa%20fa-ok%22%2C%22i_icon_themify%22%3A%22ti-location-pin%22%2C%22i_icon_sgicon%22%3A%22sgicon%20sgicon-WorldWide%22%2C%22i_icon_vc_linecons%22%3A%22li_star%22%2C%22i_icon_themestek_liviza_business_icon%22%3A%22themestek-liviza-business-icon-checklist%22%7D%2C%7B%22label%22%3A%22Immigration%20Consultency%22%2C%22value%22%3A%2280%22%2C%22add_icon%22%3A%22true%22%2C%22i_type%22%3A%22fontawesome%22%2C%22i_icon_fontawesome%22%3A%22fa%20fa-ok%22%2C%22i_icon_themify%22%3A%22ti-location-pin%22%2C%22i_icon_sgicon%22%3A%22sgicon%20sgicon-WorldWide%22%2C%22i_icon_vc_linecons%22%3A%22li_star%22%2C%22i_icon_themestek_liviza_business_icon%22%3A%22themestek-liviza-business-icon-checklist%22%7D%5D" units="%"][/vc_column][/vc_row]',
					
				),
				
				array(
					'section'	=> array('About'),
					'name'		=> esc_attr('5.jpg'),
					'img'		=> '5.jpg',
					'content'	=> '[vc_row themestek_responsive_css="74981048|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2"][vc_single_image image="13721" img_size="530*540" el_class="ts-image-shadow-1 ts-border-radius-1"][/vc_column][vc_column width="1/2" css=".vc_custom_1578378976653{padding-top: 25px !important;}"][themestek-heading h2="25 years of experience<br />
<em>Visa Immigration</em>" h4="About Agency"][/themestek-heading][vc_custom_heading text="Weve been counselling students for educational Opportun in Foreign countries." font_container="tag:h3|font_size:22px|text_align:left|line_height:36px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text]
[vc_row_inner][vc_column_inner width="1/2"][themestek-list icon_type="themestek_liviza_business_icon" icon_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-check" line1="RWR1Y2F0aW9uJTIwVmlzYQ==" line2="QnVzaW5lc3MlMjBJbW1pZ3JhdGlvbg==" line3="VG91cmlzdCUyMCUyNiUyMFZpc2l0b3IlMjBWaXNhcw==" el_class="themestek-list-sep"][/vc_column_inner][vc_column_inner width="1/2"][themestek-list icon_type="themestek_liviza_business_icon" icon_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-check" line1="TGFuZ3VhZ2UlMjBDb3Vyc2Vz" line2="RmFtaWx5JTIwVmlzYXM=" line3="V29yayUyMFBlcm1pdCUyMFZpc2E=" el_class="themestek-list-sep"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
					
			),
				array(
					'section'	=> array('Counter'),
					'name'		=> esc_attr('6.jpg'),
					'img'		=> '6.jpg',
					'content'	=> '[vc_row themestek_bgcolor="darkgrey" full_width="stretch_row" css=".vc_custom_1576300231563{background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2019/12/bg-pattarn.png?id=12910) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column]
 [vc_row_inner gap="0px" css=".vc_custom_1579689971649{padding-bottom: 40px !important;}" themestek_responsive_css="62616560|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner width="1/2" css=".vc_custom_1576300239874{padding-right: 50px !important;}"][themestek-heading h2="Since 1980 we have<br />
<em>branches all over world</em>" h4="OUR COMPANY"][/themestek-heading][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks?</p>
<p>Especially if the demographic of your audience falls in that age range. The main purpose of building prototypes is to test.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/2"][vc_single_image image="12775" img_size="full" alignment="right" css=".vc_custom_1579689988239{margin-top: 30px !important;margin-bottom: 0px !important;}" el_class="themestek-align-left-991"][/vc_column_inner][/vc_row_inner]
[vc_row_inner gap="0px" css=".vc_custom_1579690023801{margin-right: 0px !important;margin-left: 0px !important;border-top-width: 1px !important;padding-top: 50px !important;border-top-color: #404b57 !important;border-top-style: solid !important;}" el_class="themestek-two-colum-view-991-479"][vc_column_inner width="1/5"][themestek-facts-in-digits title="Trusted Clients" desc="" digit="4578" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-worker" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Countries" desc="" digit="150" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-airplane" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Universities" desc="" digit="574" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-white-house" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Students" desc="" digit="1564" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="immigration" desc="" digit="1254" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-list" after="+"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
					
				),
				array(
					'section'	=> array('Team Member'),
					'name'		=> esc_attr('7.jpg'),
					'img'		=> '7.jpg',
					'content'	=> '[vc_row][vc_column][themestek-teambox h2="Meet Our <em>Dedicated Team</em>" h4="OUR CONSULTANT" boxstyle="style-1" show="4" column="four"]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/themestek-teambox][/vc_column][/vc_row]',
					
				),
				
				array(
					'section'	=> array('Testimonial'),
					'name'		=> esc_attr('8.jpg'),
					'img'		=> '8.jpg',
					'content'	=> '[vc_row themestek_textcolor="white" themestek_bgcolor="darkgrey" full_width="stretch_row" equal_height="yes" css=".vc_custom_1579673868775{padding-top: 0px !important;padding-bottom: 0px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" themestek_responsive_css="22685741|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2" css=".vc_custom_1579600138919{padding-top: 98px !important;padding-bottom: 40px !important;}"][themestek-reviewsbox h2="NanoSoft is your <em>IT services.</em>" h2_font_container="font_size:38px|line_height:48px" h4="TESTIMONIALS" txt_align="left" boxstyle="style-1" carousel_dots="1" carousel_nav="hide" use_custom_fonts_h2="true"][/themestek-reviewsbox][/vc_column][vc_column themestek_col_bg_expand="right" width="1/2" css=".vc_custom_1579769546762{margin-top: 98px !important;margin-bottom: -115px !important;padding-top: 20px !important;padding-left: 22px !important;background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2020/01/img-06.jpg?id=13771) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-border-radius-left-bottom" themestek_responsive_css="44214750|colbreak_no|||||||||colbreak_no|0||0||150||150||colbreak_no||||||||||colbreak_no|||||||||"][themestek-iconheadingbox boxstyle="style-1" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" h2="Join students over 1000+ like you"][/themestek-iconheadingbox][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('Testimonial'),
					'name'		=> esc_attr('9.jpg'),
					'img'		=> '9.jpg',
					'content'	=> '[vc_row themestek_bgcolor="grey" full_width="stretch_row"][vc_column][themestek-reviewsbox h2="Why do people<em> praise about Us?</em>" h4="Testimonials" show="-1" column="three" carousel_dots="1" carousel_nav="hide"][/themestek-reviewsbox][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('Blog'),
					'name'		=> esc_attr('10.jpg'),
					'img'		=> '10.jpg',
					'content'	=> '[vc_row][vc_column][vc_row_inner][vc_column_inner width="1/2"][themestek-heading h2="Liviza More articles from<br />
<em>Resources &amp; News</em>" h4="Latest News"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1579674603328{margin-top: 35px !important;}" themestek_responsive_css="74839650|colbreak_no|||||||||colbreak_no|||||||||colbreak_no|0|||||||||colbreak_no|||||||||"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.The main purpose of building prototypes is to test.[/vc_column_text][/vc_column_inner][/vc_row_inner][themestek-blogbox h2="" boxstyle="style-2"][/themestek-blogbox][/vc_column][/vc_row]',
				),
				
				array(
					'section'	=> array('Blog'),
					'name'		=> esc_attr('11.jpg'),
					'img'		=> '11.jpg',
					'content'	=> '[vc_row][vc_column][vc_row_inner][vc_column_inner width="1/2"][themestek-heading h2="Liviza More articles from<br />
<em>Resources &amp; News</em>" h4="OUR COMPANY"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/2"][themestek-blogbox h2="" show="1" column="one"][/themestek-blogbox][/vc_column_inner][vc_column_inner width="1/2"][themestek-blogbox h2="" boxstyle="style-3" column="one"][/themestek-blogbox][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('project'),
					'name'		=> esc_attr('12.jpg'),
					'img'		=> '12.jpg',
					'content'	=> '[vc_row css=".vc_custom_1576297875364{padding-bottom: 50px !important;background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2019/12/map.png?id=12754) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: contain !important;}"][vc_column][themestek-portfoliobox h2="Immigration - Choose <em>your country!</em>" h4="Choose Country" boxstyle="style-1" show="4" column="four"][/themestek-portfoliobox][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('project'),
					'name'		=> esc_attr('13.jpg'),
					'img'		=> '13.jpg',
					'content'	=> '[vc_row themestek_bgcolor="skincolor" themestek_bgimage_position="center_top" full_width="stretch_row" gap="0px" css=".vc_custom_1579070930035{padding-bottom: 250px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-bg-pattarn"][vc_column][vc_row_inner themestek_textcolor="dark" content_placement="middle" gap="0px"][vc_column_inner width="1/2"][themestek-heading h2="Immigration and citizenship<br />
<em>Choose your country!</em>" h4="Choose Country"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1579686812041{margin-top: 35px !important;}" themestek_responsive_css="17032097|colbreak_no|||||||||colbreak_no|||||||||colbreak_no|0|||||||||colbreak_no|||||||||"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row themestek_bgcolor="grey" zindex="2" full_width="stretch_row" gap="0px" css=".vc_custom_1576302625292{padding-top: 0px !important;padding-bottom: 40px !important;}"][vc_column zindex="2" css=".vc_custom_1576302530416{margin-top: -200px !important;}"][themestek-portfoliobox h2="" boxstyle="style-2"][/themestek-portfoliobox][vc_column_text el_class="text-center" css=".vc_custom_1576302676829{margin-top: 30px !important;}"]Challenges are just opportunities in disguise. <a href="#">Take the challenge! </a>[/vc_column_text][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('coaching'),
					'name'		=> esc_attr('14.jpg'),
					'img'		=> '14.jpg',
					'content'	=> '[vc_row themestek_bgcolor="grey" full_width="stretch_row" gap="0px" el_class="themestek-ihbox-style-3-main" css=".vc_custom_1577957470630{padding-top: 0px !important;padding-bottom: 120px !important;}"][vc_column]
 [vc_row_inner gap="0px" css=".vc_custom_1576226958535{padding-top: 50px !important;}"][vc_column_inner width="1/2"][themestek-heading h2="Liviza is your trusted<br />
<em>Coaching Center.</em>" h4="Our Coaching"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1576218445029{margin-top: 35px !important;}"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row full_width="stretch_row"][vc_column zindex="2" css=".vc_custom_1577957483085{margin-top: -180px !important;}"][themestek-coachingbox h2="" boxstyle="style-2" show="6" column="six"][/themestek-coachingbox][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('Client'),
					'name'		=> esc_attr('15.jpg'),
					'img'		=> '15.jpg',
					'content'	=> '[vc_row full_width="stretch_row" css=".vc_custom_1578046744082{border-bottom-width: 1px !important;border-bottom-color: #e8eaeb !important;border-bottom-style: solid !important;}"][vc_column][themestek-clientsbox h2="" show_tooltip="no" add_link="no" carousel_speed="" carousel_autoplay="0" carousel_autoplayspeed="" carousel_loop="0" carousel_dots="0" carousel_nav="hide" carousel_pauseonhover="0"][/themestek-clientsbox][/vc_column][/vc_row]',
				),
				
				array(
				'section'	=> array('Icon Box'),
				'name'		=> esc_attr('16.jpg'),
				'img'		=> '16.jpg',
				'content'	=> '[vc_row themestek_bgcolor="grey" full_width="stretch_row" gap="0px" css=".vc_custom_1579672824742{padding-top: 0px !important;padding-bottom: 30px !important;}"][vc_column]
 [vc_row_inner themestek_bgcolor="white" equal_height="yes" gap="30" css=".vc_custom_1579672696864{margin-top: -120px !important;}" el_class="themestek-bg-trans" themestek_responsive_css="60911048|colbreak_no|||||||||colbreak_no|||||||||colbreak_no|50|||||||||colbreak_no|||||||||"][vc_column_inner themestek_textcolor="white" themestek_bgcolor="skincolor" el_class="ts-border-radius-1 ts-image-shadow-1" width="1/3"][themestek-iconheadingbox i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-open-book" h2="Apply Online Visa"]We are reliable immigration consultants to handle your immigration case.[/themestek-iconheadingbox][/vc_column_inner][vc_column_inner themestek_textcolor="white" themestek_bgcolor="darkgrey" el_class="ts-border-radius-1 ts-image-shadow-1" width="1/3"][themestek-iconheadingbox i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-test" h2="Book an Appointment"]To process your visa application with our experienced registered agents.[/themestek-iconheadingbox][/vc_column_inner][vc_column_inner themestek_bgcolor="white" el_class="ts-border-radius-1 ts-image-shadow-1" width="1/3"][themestek-iconheadingbox i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" h2="Immigration Experts"]Our goal has been provide immigration in all over country and universities.[/themestek-iconheadingbox][/vc_column_inner][/vc_row_inner]
 [vc_row_inner gap="0px" css=".vc_custom_1576218338476{padding-top: 50px !important;}"][vc_column_inner width="1/2"][themestek-heading h2="Liviza is your trusted<br />
<em>Consulting Visa</em>" h4="Who we are"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1579673501614{margin-top: 25px !important;}" themestek_responsive_css="55328164|colbreak_no|||||||||colbreak_no|||||||||colbreak_no|0|||||||||colbreak_no|||||||||"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('CTA'),
					'name'		=> esc_attr('17.jpg'),
					'img'		=> '17.jpg',
					'content'	=> '[vc_row equal_height="yes" css=".vc_custom_1578649967120{margin-top: -150px !important;padding-top: 0px !important;padding-bottom: 0px !important;}"][vc_column css=".vc_custom_1579673650886{margin-right: 15px !important;margin-left: 15px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" themestek_responsive_css="87367965|colbreak_no|||||||||colbreak_no|||||||||colbreak_no||0||0||||||colbreak_no|||||||||"]
 [vc_row_inner themestek_bgcolor="white" equal_height="yes" gap="0px" el_class="ts-border-radius-2 ts-image-shadow-2"][vc_column_inner width="5/12" css=".vc_custom_1579762893190{background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2020/01/img-02.jpg?id=13722) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][/vc_column_inner][vc_column_inner width="7/12" css=".vc_custom_1579683066798{padding-top: 40px !important;padding-right: 40px !important;padding-bottom: 40px !important;padding-left: 60px !important;}" themestek_responsive_css="46208162|colbreak_no|||||||||colbreak_no|||||||||colbreak_no||||||30||30||colbreak_no|||||||||"][vc_custom_heading text="Free Online Visa Assessment" font_container="tag:div|font_size:30px|text_align:left|color:%232d3845|line_height:30px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:700%20bold%20regular%3A700%3Anormal" css=".vc_custom_1576297376311{margin-bottom: 10px !important;}"][vc_custom_heading text="Contact us today by fill up free online visa assessment and we will contact you" font_container="tag:p|font_size:20px|text_align:left|color:%232d3845|line_height:30px" google_fonts="font_family:Lato%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][themestek-btn title="Discover More" style="classic" font_weight="no" css=".vc_custom_1578648654194{margin-bottom: 0px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('CTA'),
					'name'		=> esc_attr('18.jpg'),
					'img'		=> '18.jpg',
					'content'	=> '[vc_row themestek_bgcolor="skincolor" full_width="stretch_row" css=".vc_custom_1579685791667{padding-top: 110px !important;padding-bottom: 80px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-bg-pattarn-3" themestek_responsive_css="55768038|colbreak_yes|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="3/4"][themestek-heading h2="We run all kinds of immigration <em>Services that vow your success</em>"][/themestek-heading][/vc_column][vc_column width="1/4" themestek_responsive_css="43558640|colbreak_no|0||||||||colbreak_no|||||||||colbreak_no||||||||||colbreak_no|||||||||" css=".vc_custom_1579685925684{margin-top: 30px !important;}"][themestek-btn title="Get Free Assessment" style="outline" color="white" size="lg" font_weight="no"][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('Pages'),
					'name'		=> esc_attr('19.jpg'),
					'img'		=> '19.jpg',
					'content'	=> '[vc_row themestek_bgcolor="grey" full_width="stretch_row" gap="0px" css=".vc_custom_1579672824742{padding-top: 0px !important;padding-bottom: 30px !important;}"][vc_column]
 [vc_row_inner themestek_bgcolor="white" equal_height="yes" gap="30" css=".vc_custom_1579672696864{margin-top: -120px !important;}" el_class="themestek-bg-trans" themestek_responsive_css="60911048|colbreak_no|||||||||colbreak_no|||||||||colbreak_no|50|||||||||colbreak_no|||||||||"][vc_column_inner themestek_textcolor="white" themestek_bgcolor="skincolor" el_class="ts-border-radius-1 ts-image-shadow-1" width="1/3"][themestek-iconheadingbox i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-open-book" h2="Apply Online Visa"]We are reliable immigration consultants to handle your immigration case.[/themestek-iconheadingbox][/vc_column_inner][vc_column_inner themestek_textcolor="white" themestek_bgcolor="darkgrey" el_class="ts-border-radius-1 ts-image-shadow-1" width="1/3"][themestek-iconheadingbox i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-test" h2="Book an Appointment"]To process your visa application with our experienced registered agents.[/themestek-iconheadingbox][/vc_column_inner][vc_column_inner themestek_bgcolor="white" el_class="ts-border-radius-1 ts-image-shadow-1" width="1/3"][themestek-iconheadingbox i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" h2="Immigration Experts"]Our goal has been provide immigration in all over country and universities.[/themestek-iconheadingbox][/vc_column_inner][/vc_row_inner]
 [vc_row_inner gap="0px" css=".vc_custom_1576218338476{padding-top: 50px !important;}"][vc_column_inner width="1/2"][themestek-heading h2="Liviza is your trusted<br />
<em>Consulting Visa</em>" h4="Who we are"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1579673501614{margin-top: 25px !important;}" themestek_responsive_css="55328164|colbreak_no|||||||||colbreak_no|||||||||colbreak_no|0|||||||||colbreak_no|||||||||"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row themestek_responsive_css="66659895|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2" css=".vc_custom_1576296341647{padding-bottom: 150px !important;}"][vc_single_image image="13722" img_size="470*470" el_class="ts-image-shadow-1 ts-border-radius-1"][vc_single_image image="13721" img_size="370*275" el_class="ts-promo-image-1 ts-border-radius-1"][themestek-icon type="themestek_liviza_business_icon" icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" color="white" background_style="rounded" background_color="skincolor" size="xl" el_class="ts-brand-icon"][/vc_column][vc_column width="1/2" css=".vc_custom_1576297121934{padding-top: 30px !important;}"][themestek-heading h2="Immigration Services From<br />
<em>Experienced Lawyers.</em>" h4="About Agency"][/themestek-heading][vc_custom_heading text="Weve been counselling students for educational Opportun in Foreign countries." font_container="tag:h3|font_size:22px|text_align:left|line_height:36px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text][themestek-list icon_type="themestek_liviza_business_icon" icon_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-check" line1="VGFsayUyMHRvJTIwb25lJTIwb2YlMjBvdXIlMjBiZXN0JTIwY29uc3VsdGFudCUyMHRvZGF5" line2="T3VyJTIwZXhwZXJ0cyUyMGFyZSUyMGFibGUlMjB0byUyMGZpbmQlMjBuZXclMjBncm93dGg=" line3="RmluZCUyMG1vcmUlMjBpbmZvcm1hdGlvbiUyMG91ciUyMHdlYnNpdGU=" el_class="themestek-list-sep"][themestek-btn title="Discover More" style="classic"][/vc_column][/vc_row]
[vc_row themestek_textcolor="white" themestek_bgcolor="darkgrey" full_width="stretch_row" css=".vc_custom_1579083957325{padding-bottom: 200px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-bg-pattarn-2"][vc_column zindex="1"]
[vc_row_inner][vc_column_inner width="1/2"][themestek-heading h2="Liviza Immigration Visa<br />
<em>Service We Provide</em>" h4="Our Service"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1576219307436{margin-top: 35px !important;}"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text][/vc_column_inner][/vc_row_inner][themestek-servicebox h2="" boxstyle="style-1" show="-1" column="four" boxview="carousel" carousel_dots="1" carousel_nav="hide"][/themestek-servicebox][/vc_column][/vc_row]
[vc_row equal_height="yes" css=".vc_custom_1578649967120{margin-top: -150px !important;padding-top: 0px !important;padding-bottom: 0px !important;}"][vc_column css=".vc_custom_1579673650886{margin-right: 15px !important;margin-left: 15px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" themestek_responsive_css="87367965|colbreak_no|||||||||colbreak_no|||||||||colbreak_no||0||0||||||colbreak_no|||||||||"]
 [vc_row_inner themestek_bgcolor="white" equal_height="yes" gap="0px" el_class="ts-border-radius-2 ts-image-shadow-2"][vc_column_inner width="5/12" css=".vc_custom_1579762893190{background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2020/01/img-02.jpg?id=13722) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][/vc_column_inner][vc_column_inner width="7/12" css=".vc_custom_1579683066798{padding-top: 40px !important;padding-right: 40px !important;padding-bottom: 40px !important;padding-left: 60px !important;}" themestek_responsive_css="46208162|colbreak_no|||||||||colbreak_no|||||||||colbreak_no||||||30||30||colbreak_no|||||||||"][vc_custom_heading text="Free Online Visa Assessment" font_container="tag:div|font_size:30px|text_align:left|color:%232d3845|line_height:30px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:700%20bold%20regular%3A700%3Anormal" css=".vc_custom_1576297376311{margin-bottom: 10px !important;}"][vc_custom_heading text="Contact us today by fill up free online visa assessment and we will contact you" font_container="tag:p|font_size:20px|text_align:left|color:%232d3845|line_height:30px" google_fonts="font_family:Lato%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][themestek-btn title="Discover More" style="classic" font_weight="no" css=".vc_custom_1578648654194{margin-bottom: 0px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row css=".vc_custom_1576297875364{padding-bottom: 50px !important;background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2019/12/map.png?id=12754) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: contain !important;}"][vc_column][themestek-portfoliobox h2="Immigration - Choose <em>your country!</em>" h4="Choose Country" boxstyle="style-1" show="4" column="four"][/themestek-portfoliobox][/vc_column][/vc_row]
[vc_row themestek_textcolor="white" themestek_bgcolor="darkgrey" full_width="stretch_row" equal_height="yes" css=".vc_custom_1579673868775{padding-top: 0px !important;padding-bottom: 0px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" themestek_responsive_css="22685741|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2" css=".vc_custom_1579600138919{padding-top: 98px !important;padding-bottom: 40px !important;}"][themestek-reviewsbox h2="NanoSoft is your <em>IT services.</em>" h2_font_container="font_size:38px|line_height:48px" h4="TESTIMONIALS" txt_align="left" boxstyle="style-1" carousel_dots="1" carousel_nav="hide" use_custom_fonts_h2="true"][/themestek-reviewsbox][/vc_column][vc_column themestek_col_bg_expand="right" width="1/2" css=".vc_custom_1579771426869{margin-top: 98px !important;margin-bottom: -115px !important;padding-top: 20px !important;padding-left: 22px !important;background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2020/01/img-06.jpg?id=13771) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-border-radius-left-bottom" themestek_responsive_css="44214750|colbreak_no|||||||||colbreak_no|0||0||150||150||colbreak_no||||||||||colbreak_no|||||||||"][themestek-iconheadingbox boxstyle="style-1" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" h2="Join students over 1000+ like you"][/themestek-iconheadingbox][/vc_column][/vc_row]
[vc_row themestek_bgcolor="grey" full_width="stretch_row" css=".vc_custom_1579674092379{padding-top: 40px !important;padding-bottom: 40px !important;}" themestek_responsive_css="12966459|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2"]
 [vc_row_inner][vc_column_inner width="1/2"][themestek-facts-in-digits boxstyle="style-4" title="Our Satisfied Customers" after="%"][/vc_column_inner][vc_column_inner width="1/2"][themestek-facts-in-digits boxstyle="style-4" title="Projects are Completed" digit="75" after="%"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2"][/vc_column][/vc_row]
 [vc_row][vc_column][vc_row_inner][vc_column_inner width="1/2"][themestek-heading h2="Liviza More articles from<br />
<em>Resources &amp; News</em>" h4="Latest News"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1579674603328{margin-top: 35px !important;}" themestek_responsive_css="74839650|colbreak_no|||||||||colbreak_no|||||||||colbreak_no|0|||||||||colbreak_no|||||||||"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.The main purpose of building prototypes is to test.[/vc_column_text][/vc_column_inner][/vc_row_inner][themestek-blogbox h2="" boxstyle="style-2"][/themestek-blogbox][/vc_column][/vc_row]',
				),

				array(
					'section'	=> array('Pages'),
					'name'		=> esc_attr('20.jpg'),
					'img'		=> '20.jpg',
					'content'	=> '[vc_row themestek_bgcolor="grey" full_width="stretch_row" gap="0px" el_class="themestek-ihbox-style-3-main" css=".vc_custom_1577957470630{padding-top: 0px !important;padding-bottom: 120px !important;}"][vc_column]
 [vc_row_inner gap="0px" css=".vc_custom_1576226958535{padding-top: 50px !important;}"][vc_column_inner width="1/2"][themestek-heading h2="Liviza is your trusted<br />
<em>Coaching Center.</em>" h4="Our Coaching"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1576218445029{margin-top: 35px !important;}"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row full_width="stretch_row"][vc_column zindex="2" css=".vc_custom_1577957483085{margin-top: -180px !important;}"][themestek-coachingbox h2="" boxstyle="style-2" show="6" column="six"][/themestek-coachingbox][/vc_column][/vc_row]
[vc_row themestek_bgimage_position="center_bottom" css=".vc_custom_1577957491383{padding-top: 0px !important;padding-bottom: 40px !important;background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2019/12/bg-pattarn-02.png?id=12913) !important;background-position: 0 0 !important;background-repeat: no-repeat !important;}" el_class="themestek-servicebox-style-2-space"][vc_column][themestek-servicebox h2="Immigration - Choose<em> your country!</em>" h4="Immigration" boxstyle="style-2"]With a community of over 400 million users and a majority age group being 18 to 29 wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/themestek-servicebox][/vc_column][/vc_row]
[vc_row themestek_bgcolor="darkgrey" full_width="stretch_row" css=".vc_custom_1576300231563{background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2019/12/bg-pattarn.png?id=12910) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column]
 [vc_row_inner gap="0px" css=".vc_custom_1579686062552{padding-bottom: 40px !important;}" themestek_responsive_css="91337980|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner width="1/2" css=".vc_custom_1576300239874{padding-right: 50px !important;}"][themestek-heading h2="Since 1980 we have<br />
<em>branches all over world</em>" h4="OUR COMPANY"][/themestek-heading][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks?</p>
<p>Especially if the demographic of your audience falls in that age range. The main purpose of building prototypes is to test.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/2"][vc_single_image image="12775" img_size="full" alignment="right" css=".vc_custom_1579686242553{margin-top: 30px !important;margin-bottom: 0px !important;}" el_class="themestek-align-left-991"][/vc_column_inner][/vc_row_inner]
[vc_row_inner gap="0px" css=".vc_custom_1579684350367{margin-right: 0px !important;margin-left: 0px !important;border-top-width: 1px !important;padding-top: 50px !important;border-top-color: #404b57 !important;border-top-style: solid !important;}" el_class="themestek-two-colum-view-991-479"][vc_column_inner width="1/5"][themestek-facts-in-digits title="Trusted Clients" desc="" digit="4578" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-worker" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Countries" desc="" digit="150" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-airplane" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Universities" desc="" digit="574" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-white-house" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Students" desc="" digit="1564" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="immigration" desc="" digit="1254" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-list" after="+"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row themestek_responsive_css="74138818|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2"][vc_single_image image="13722" img_size="530*540" el_class="ts-image-shadow-1 ts-border-radius-1" css=".vc_custom_1579763100924{margin-bottom: 20px !important;}"][themestek-icon type="fontawesome" icon_fontawesome="fa fa-play" color="white" background_style="rounded" background_color="skincolor" size="xl" align="right" el_class="ts-brand-icon-1"][/vc_column][vc_column width="1/2" css=".vc_custom_1579685179319{padding-top: 30px !important;padding-left: 60px !important;}" themestek_responsive_css="52206995|colbreak_no||||||15||15|colbreak_no|||||||||colbreak_no||||||||||colbreak_no|||||||||"][themestek-heading h2="Immigration Services From<br />
<em>Experienced Lawyers</em>" h4="About Agency"][/themestek-heading][vc_custom_heading text="Weve been counselling students for educational Opportun in Foreign countries." font_container="tag:h3|font_size:22px|text_align:left|line_height:36px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text][themestek-progress-bar values="%5B%7B%22label%22%3A%22Student%20Consultency%22%2C%22value%22%3A%2290%22%2C%22add_icon%22%3A%22true%22%2C%22i_type%22%3A%22fontawesome%22%2C%22i_icon_fontawesome%22%3A%22fa%20fa-ok%22%2C%22i_icon_themify%22%3A%22ti-location-pin%22%2C%22i_icon_sgicon%22%3A%22sgicon%20sgicon-WorldWide%22%2C%22i_icon_vc_linecons%22%3A%22li_star%22%2C%22i_icon_themestek_liviza_business_icon%22%3A%22themestek-liviza-business-icon-checklist%22%7D%2C%7B%22label%22%3A%22Immigration%20Consultency%22%2C%22value%22%3A%2280%22%2C%22add_icon%22%3A%22true%22%2C%22i_type%22%3A%22fontawesome%22%2C%22i_icon_fontawesome%22%3A%22fa%20fa-ok%22%2C%22i_icon_themify%22%3A%22ti-location-pin%22%2C%22i_icon_sgicon%22%3A%22sgicon%20sgicon-WorldWide%22%2C%22i_icon_vc_linecons%22%3A%22li_star%22%2C%22i_icon_themestek_liviza_business_icon%22%3A%22themestek-liviza-business-icon-checklist%22%7D%5D" units="%"][/vc_column][/vc_row]
[vc_row themestek_bgcolor="skincolor" full_width="stretch_row" css=".vc_custom_1579685791667{padding-top: 110px !important;padding-bottom: 80px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-bg-pattarn-3" themestek_responsive_css="55768038|colbreak_yes|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="3/4"][themestek-heading h2="We run all kinds of immigration <em>Services that vow your success</em>"][/themestek-heading][/vc_column][vc_column width="1/4" themestek_responsive_css="43558640|colbreak_no|0||||||||colbreak_no|||||||||colbreak_no||||||||||colbreak_no|||||||||" css=".vc_custom_1579685925684{margin-top: 30px !important;}"][themestek-btn title="Get Free Assessment" style="outline" color="white" size="lg" font_weight="no"][/vc_column][/vc_row]
[vc_row themestek_bgcolor="grey" full_width="stretch_row"][vc_column][themestek-reviewsbox h2="Why do people<em> praise about Us?</em>" h4="Testimonials" show="-1" column="three" carousel_dots="1" carousel_nav="hide"][/themestek-reviewsbox][/vc_column][/vc_row]
[vc_row full_width="stretch_row" css=".vc_custom_1578046744082{border-bottom-width: 1px !important;border-bottom-color: #e8eaeb !important;border-bottom-style: solid !important;}"][vc_column][themestek-clientsbox h2="" show_tooltip="no" add_link="no" carousel_speed="" carousel_autoplay="0" carousel_autoplayspeed="" carousel_loop="0" carousel_dots="0" carousel_nav="hide" carousel_pauseonhover="0"][/themestek-clientsbox][/vc_column][/vc_row]
 [vc_row][vc_column][vc_row_inner][vc_column_inner width="1/2"][themestek-heading h2="Liviza More articles from<br />
<em>Resources &amp; News</em>" h4="OUR COMPANY"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/2"][themestek-blogbox h2="" show="1" column="one"][/themestek-blogbox][/vc_column_inner][vc_column_inner width="1/2"][themestek-blogbox h2="" boxstyle="style-3" column="one"][/themestek-blogbox][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
				),

				array(
					'section'	=> array('Pages'),
					'name'		=> esc_attr('21.jpg'),
					'img'		=> '21.jpg',
					'content'	=> '[vc_row themestek_bgcolor="skincolor" themestek_bgimage_position="center_top" full_width="stretch_row" gap="0px" css=".vc_custom_1579070930035{padding-bottom: 250px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-bg-pattarn"][vc_column][vc_row_inner themestek_textcolor="dark" content_placement="middle" gap="0px"][vc_column_inner width="1/2"][themestek-heading h2="Immigration and citizenship<br />
<em>Choose your country!</em>" h4="Choose Country"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1579686812041{margin-top: 35px !important;}" themestek_responsive_css="17032097|colbreak_no|||||||||colbreak_no|||||||||colbreak_no|0|||||||||colbreak_no|||||||||"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row themestek_bgcolor="grey" zindex="2" full_width="stretch_row" gap="0px" css=".vc_custom_1576302625292{padding-top: 0px !important;padding-bottom: 40px !important;}"][vc_column zindex="2" css=".vc_custom_1576302530416{margin-top: -200px !important;}"][themestek-portfoliobox h2="" boxstyle="style-2"][/themestek-portfoliobox][vc_column_text el_class="text-center" css=".vc_custom_1576302676829{margin-top: 30px !important;}"]Challenges are just opportunities in disguise. <a href="#">Take the challenge! </a>[/vc_column_text][/vc_column][/vc_row]
[vc_row themestek_responsive_css="31496500|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2"][vc_single_image image="13721" img_size="530*540" el_class="ts-image-shadow-1 ts-border-radius-1" css=".vc_custom_1579763187109{margin-bottom: 20px !important;}"][themestek-icon type="fontawesome" icon_fontawesome="fa fa-play" color="white" background_style="rounded" background_color="skincolor" size="xl" align="right" el_class="ts-brand-icon-1"][/vc_column][vc_column width="1/2" css=".vc_custom_1579686891878{padding-top: 30px !important;padding-left: 60px !important;}" themestek_responsive_css="87056409|colbreak_no|||||||||colbreak_no||||||||15|colbreak_no||||||||||colbreak_no|||||||||"][themestek-heading h2="Immigration Services From<br />
<em>Experienced Lawyers</em>" h4="About Agency"][/themestek-heading][vc_custom_heading text="Weve been counselling students for educational Opportun in Foreign countries." font_container="tag:h3|font_size:22px|text_align:left|line_height:36px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text][themestek-progress-bar values="%5B%7B%22label%22%3A%22Student%20Consultency%22%2C%22value%22%3A%2290%22%2C%22add_icon%22%3A%22true%22%2C%22i_type%22%3A%22fontawesome%22%2C%22i_icon_fontawesome%22%3A%22fa%20fa-ok%22%2C%22i_icon_themify%22%3A%22ti-location-pin%22%2C%22i_icon_sgicon%22%3A%22sgicon%20sgicon-WorldWide%22%2C%22i_icon_vc_linecons%22%3A%22li_star%22%2C%22i_icon_themestek_liviza_business_icon%22%3A%22themestek-liviza-business-icon-checklist%22%7D%2C%7B%22label%22%3A%22Immigration%20Consultency%22%2C%22value%22%3A%2280%22%2C%22add_icon%22%3A%22true%22%2C%22i_type%22%3A%22fontawesome%22%2C%22i_icon_fontawesome%22%3A%22fa%20fa-ok%22%2C%22i_icon_themify%22%3A%22ti-location-pin%22%2C%22i_icon_sgicon%22%3A%22sgicon%20sgicon-WorldWide%22%2C%22i_icon_vc_linecons%22%3A%22li_star%22%2C%22i_icon_themestek_liviza_business_icon%22%3A%22themestek-liviza-business-icon-checklist%22%7D%5D" units="%"][/vc_column][/vc_row]
[vc_row themestek_textcolor="white" themestek_bgcolor="darkgrey" full_width="stretch_row" css=".vc_custom_1579087835996{padding-bottom: 200px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-bg-pattarn-2"][vc_column zindex="1"]
 [vc_row_inner][vc_column_inner width="1/2"][themestek-heading h2="Liviza Immigration Visa<br />
<em>Service We Provide.</em>" h4="OUR COMPANY"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1576219307436{margin-top: 35px !important;}"][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text][/vc_column_inner][/vc_row_inner][themestek-servicebox h2="" boxstyle="style-1" show="-1" column="four" boxview="carousel" carousel_dots="1" carousel_nav="hide"][/themestek-servicebox][/vc_column][/vc_row]
[vc_row equal_height="yes" css=".vc_custom_1578649967120{margin-top: -150px !important;padding-top: 0px !important;padding-bottom: 0px !important;}"][vc_column css=".vc_custom_1578650026649{margin-right: 15px !important;margin-left: 15px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"]
 [vc_row_inner themestek_bgcolor="white" equal_height="yes" gap="0px" el_class="ts-border-radius-2 ts-image-shadow-2"][vc_column_inner width="5/12" css=".vc_custom_1579763201082{background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2020/01/img-02.jpg?id=13722) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][/vc_column_inner][vc_column_inner width="7/12" css=".vc_custom_1578649855365{padding-top: 40px !important;padding-right: 40px !important;padding-bottom: 40px !important;padding-left: 60px !important;}"][vc_custom_heading text="Free Online Visa Assessment" font_container="tag:div|font_size:30px|text_align:left|color:%232d3845|line_height:30px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:700%20bold%20regular%3A700%3Anormal" css=".vc_custom_1576297376311{margin-bottom: 10px !important;}"][vc_custom_heading text="Contact us today by fill up free online visa assessment and we will contact you" font_container="tag:p|font_size:20px|text_align:left|color:%232d3845|line_height:30px" google_fonts="font_family:Lato%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][themestek-btn title="Discover More" style="classic" font_weight="no" css=".vc_custom_1578648654194{margin-bottom: 0px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row themestek_bgimage_position="center_bottom" css=".vc_custom_1576303145160{padding-bottom: 30px !important;background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2019/12/bg-pattarn-02.png?id=12913) !important;background-position: 0 0 !important;background-repeat: no-repeat !important;}"][vc_column][themestek-teambox h2="Meet Our <em>Dedicated Team</em>" h4="Our Consultant" boxstyle="style-1" show="4" column="four"]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/themestek-teambox][vc_column_text el_class="text-center"]Challenges are just opportunities in disguise. <a href="#">Take the challenge! </a>[/vc_column_text][/vc_column][/vc_row]
[vc_row themestek_bgcolor="skincolor" full_width="stretch_row" css=".vc_custom_1579087880436{padding-top: 110px !important;padding-bottom: 80px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-bg-pattarn-3"][vc_column width="9/12"][themestek-heading h2="We run all kinds of immigration <em>Services that vow your success</em>"][/themestek-heading][/vc_column][vc_column width="3/12"][themestek-btn title="Get Free Assessment" style="outline" color="white" size="lg" font_weight="no" css=".vc_custom_1579322353846{margin-top: 30px !important;}"][/vc_column][/vc_row]
[vc_row full_width="stretch_row" css=".vc_custom_1578046744082{border-bottom-width: 1px !important;border-bottom-color: #e8eaeb !important;border-bottom-style: solid !important;}"][vc_column][themestek-clientsbox h2="" show="5" show_tooltip="no" add_link="no" carousel_speed="" carousel_autoplay="0" carousel_autoplayspeed="" carousel_loop="0" carousel_dots="0" carousel_nav="hide" carousel_pauseonhover="0"][/themestek-clientsbox][/vc_column][/vc_row]
 [vc_row][vc_column][vc_row_inner][vc_column_inner width="1/2"][themestek-heading h2="Liviza More articles from<br />
<em>Resources &amp; News</em>" h4="OUR COMPANY"][/themestek-heading][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1576219307436{margin-top: 35px !important;}"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text][/vc_column_inner][/vc_row_inner][themestek-blogbox h2="" boxstyle="style-2"][/themestek-blogbox][/vc_column][/vc_row]',
				),
				array(
					'section'	=> array('Pages'),
					'name'		=> esc_attr('22.jpg'),
					'img'		=> '22.jpg',
					'content'	=> '[vc_row themestek_responsive_css="74981048|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2"][vc_single_image image="13721" img_size="530*540" el_class="ts-image-shadow-1 ts-border-radius-1"][/vc_column][vc_column width="1/2" css=".vc_custom_1578378976653{padding-top: 25px !important;}"][themestek-heading h2="25 years of experience<br />
<em>Visa Immigration</em>" h4="About Agency"][/themestek-heading][vc_custom_heading text="Weve been counselling students for educational Opportun in Foreign countries." font_container="tag:h3|font_size:22px|text_align:left|line_height:36px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal"][vc_column_text]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/vc_column_text]
[vc_row_inner][vc_column_inner width="1/2"][themestek-list icon_type="themestek_liviza_business_icon" icon_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-check" line1="RWR1Y2F0aW9uJTIwVmlzYQ==" line2="QnVzaW5lc3MlMjBJbW1pZ3JhdGlvbg==" line3="VG91cmlzdCUyMCUyNiUyMFZpc2l0b3IlMjBWaXNhcw==" el_class="themestek-list-sep"][/vc_column_inner][vc_column_inner width="1/2"][themestek-list icon_type="themestek_liviza_business_icon" icon_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-check" line1="TGFuZ3VhZ2UlMjBDb3Vyc2Vz" line2="RmFtaWx5JTIwVmlzYXM=" line3="V29yayUyMFBlcm1pdCUyMFZpc2E=" el_class="themestek-list-sep"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row themestek_bgcolor="darkgrey" full_width="stretch_row" css=".vc_custom_1576300231563{background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2019/12/bg-pattarn.png?id=12910) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column]
 [vc_row_inner gap="0px" css=".vc_custom_1579689971649{padding-bottom: 40px !important;}" themestek_responsive_css="62616560|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column_inner width="1/2" css=".vc_custom_1576300239874{padding-right: 50px !important;}"][themestek-heading h2="Since 1980 we have<br />
<em>branches all over world</em>" h4="OUR COMPANY"][/themestek-heading][vc_column_text]With a community of over 400 million users and a majority age group being 18 to 29, wouldn’t you want to make sure you’re monitoring what people are posting on social networks?</p>
<p>Especially if the demographic of your audience falls in that age range. The main purpose of building prototypes is to test.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/2"][vc_single_image image="12775" img_size="full" alignment="right" css=".vc_custom_1579689988239{margin-top: 30px !important;margin-bottom: 0px !important;}" el_class="themestek-align-left-991"][/vc_column_inner][/vc_row_inner]
[vc_row_inner gap="0px" css=".vc_custom_1579690023801{margin-right: 0px !important;margin-left: 0px !important;border-top-width: 1px !important;padding-top: 50px !important;border-top-color: #404b57 !important;border-top-style: solid !important;}" el_class="themestek-two-colum-view-991-479"][vc_column_inner width="1/5"][themestek-facts-in-digits title="Trusted Clients" desc="" digit="4578" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-worker" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Countries" desc="" digit="150" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-airplane" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Universities" desc="" digit="574" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-white-house" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="Students" desc="" digit="1564" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" after="+"][/vc_column_inner][vc_column_inner width="1/5"][themestek-facts-in-digits title="immigration" desc="" digit="1254" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-list" after="+"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
[vc_row][vc_column][themestek-teambox h2="Meet Our <em>Dedicated Team</em>" h4="OUR CONSULTANT" boxstyle="style-1" show="4" column="four"]With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks?[/themestek-teambox][/vc_column][/vc_row]
[vc_row themestek_textcolor="white" themestek_bgcolor="darkgrey" full_width="stretch_row" equal_height="yes" css=".vc_custom_1579673868775{padding-top: 0px !important;padding-bottom: 0px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" themestek_responsive_css="22685741|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2" css=".vc_custom_1579600138919{padding-top: 98px !important;padding-bottom: 40px !important;}"][themestek-reviewsbox h2="NanoSoft is your <em>IT services.</em>" h2_font_container="font_size:38px|line_height:48px" h4="TESTIMONIALS" txt_align="left" boxstyle="style-1" carousel_dots="1" carousel_nav="hide" use_custom_fonts_h2="true"][/themestek-reviewsbox][/vc_column][vc_column themestek_col_bg_expand="right" width="1/2" css=".vc_custom_1579769546762{margin-top: 98px !important;margin-bottom: -115px !important;padding-top: 20px !important;padding-left: 22px !important;background-image: url(http://liviza.themestek2.com/datasite/wp-content/uploads/sites/6/2020/01/img-06.jpg?id=13771) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="themestek-border-radius-left-bottom" themestek_responsive_css="44214750|colbreak_no|||||||||colbreak_no|0||0||150||150||colbreak_no||||||||||colbreak_no|||||||||"][themestek-iconheadingbox boxstyle="style-1" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-student" h2="Join students over 1000+ like you"][/themestek-iconheadingbox][/vc_column][/vc_row]
[vc_row themestek_bgcolor="grey" full_width="stretch_row" css=".vc_custom_1579674092379{padding-top: 40px !important;padding-bottom: 40px !important;}" themestek_responsive_css="12966459|colbreak_no|||||||||colbreak_yes|||||||||colbreak_no||||||||||colbreak_no|||||||||"][vc_column width="1/2"]
 [vc_row_inner][vc_column_inner width="1/2"][themestek-facts-in-digits boxstyle="style-4" title="Our Satisfied Customers" after="%"][/vc_column_inner][vc_column_inner width="1/2"][themestek-facts-in-digits boxstyle="style-4" title="Projects are Completed" digit="75" after="%"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2"][/vc_column][/vc_row]
[vc_row full_width="stretch_row"][vc_column][themestek-clientsbox h2="" show="5" show_tooltip="no" add_link="no" boxview="default"][/themestek-clientsbox][/vc_column][/vc_row]',
				), 
				array(
					'section'	=> array('Pages'),
					'name'		=> esc_attr('23.jpg'),
					'img'		=> '23.jpg',
					'content'	=> '[vc_row][vc_column width="1/3"][themestek-iconheadingbox boxstyle="style-2" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-placeholder" h2="Our Address"]51 Somestreet Cambridge,
CB4 3AA, United Kingdom[/themestek-iconheadingbox][/vc_column][vc_column width="1/3"][themestek-iconheadingbox boxstyle="style-2" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-call" h2="Phone Number"]Mobile: (+88) 090 1900 – 6886
Hotline: 1800 6886[/themestek-iconheadingbox][/vc_column][vc_column width="1/3"][themestek-iconheadingbox boxstyle="style-2" i_type="themestek_liviza_business_icon" i_icon_themestek_liviza_business_icon="themestek-liviza-business-icon themestek-liviza-business-icon-envelope" h2="Email Address"]info@website.com
sales@website.com[/themestek-iconheadingbox][/vc_column][/vc_row][vc_row css=".vc_custom_1576473295771{padding-top: 0px !important;padding-bottom: 90px !important;}"][vc_column][vc_row_inner equal_height="yes" gap="0px" css=".vc_custom_1576472909816{margin-right: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-bottom: 0px !important;}" el_class="ts-border-radius-2 ts-image-shadow-2"][vc_column_inner width="1/2" css=".vc_custom_1576471537997{padding-left: 0px !important;}"][vc_raw_html css=".vc_custom_1576473382617{margin-bottom: 0px !important;}"]JTNDZGl2JTIwc3R5bGUlM0QlMjJoZWlnaHQlM0E1OTBweCUzQiUyMiUzRSUwQSUzQ2lmcmFtZSUyMHNyYyUzRCUyMmh0dHBzJTNBJTJGJTJGd3d3Lmdvb2dsZS5jb20lMkZtYXBzJTJGZW1iZWQlM0ZwYiUzRCUyMTFtMTglMjExbTEyJTIxMW0zJTIxMWQzMzE1LjAwODU3NTM1NjEwNTclMjEyZC0xMTcuOTIxMTYyODg0MzY4MTclMjEzZDMzLjgxMjA5MTc4MDY3MTkzNSUyMTJtMyUyMTFmMCUyMTJmMCUyMTNmMCUyMTNtMiUyMTFpMTAyNCUyMTJpNzY4JTIxNGYxMy4xJTIxM20zJTIxMW0yJTIxMXMweDgwZGNkN2QxMmIzYjVlNmIlMjUzQTB4MmVmNjJmODQxODIyNWNmYSUyMTJzRGlzbmV5bGFuZCUyQlBhcmslMjE1ZTAlMjEzbTIlMjExc2VuJTIxMnNpbiUyMTR2MTU0MjE5MzQ1ODg2NiUyMiUyMHdpZHRoJTNEJTIyNjAwJTIyJTIwaGVpZ2h0JTNEJTIyNTkwJTIyJTIwZnJhbWVib3JkZXIlM0QlMjIwJTIyJTIwc3R5bGUlM0QlMjJib3JkZXIlM0EwJTNCJTIwd2lkdGglM0ExMDAlMjUlM0IlMjIlMjBhbGxvd2Z1bGxzY3JlZW4lM0UlM0MlMkZpZnJhbWUlM0UlM0MlMkZkaXYlM0U=[/vc_raw_html][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1576473344088{padding-top: 50px !important;padding-right: 40px !important;padding-bottom: 0px !important;padding-left: 20px !important;}"][themestek-heading h2="Get in <em>touch</em>" h4="Contact Us"][/themestek-heading][contact-form-7 id="10414"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
				), 
			
				
				
				

		);

		return isset( $p[ $n ] ) ? $p[ $n ] : $p;
	}
}